---
# Replace with your collection requirements or delete this file entirely if you do not
# need it.
collections:
  - name: ansible.posix
    # version: "1.5.4"

  - name: community.general
    # version: ">=8.3.0"
